### ISSUE TITLE
Startup-script

### ISSUE THREAD

**Issue by esticle** [manios/docker-nagios#10]
Hi,

As reminded in Issue#9 earlier, my (very newbie) workflow to test any new container is pretty much:

`# docker pull manios/nagios && docker stop nagios && docker rm nagios && docker-compose -f nagios.yaml up -d && docker tag <imageid> `date +%s` # to keep tabs `

Which leads to the question - where is an appropriate point I can put a script that will be run on start so it can do my usual stuff (set TZ, add some packages and nagios plugins, etc etc), ie. a /etc/rc.local or /etc/cont-init.d/ equivalent?

Thanks!

**Comment by manios** [comment]
Hi @esticle ,

Sorry for the delay, unfortunately I had no time for open source :smile:  things! The startup script for this container is [start_nagios](https://github.com/manios/docker-nagios/blob/dokimes/overlay/usr/local/bin/start_nagios) which is executed in the `CMD` section of the [Dockerfile](https://github.com/manios/docker-nagios/blob/dokimes/Dockerfile). 

You can do whatever you want in there, override it or extend it.

Best regards,
Christos

**Comment by esticle** [comment]
No worries about time, I got the same problems :)
I'll rtfm a bit around runit to save some post-creation-hassles, thanks!
