### ISSUE TITLE
Add the ability to override default timezone inside the container and Nagios

### ISSUE THREAD

**Issue by manios** [manios/docker-nagios#11]
At the moment the Alpine container and Nagios both use `UTC`. In order to change the timezone we need to do some manual steps (described in #9) for every container.

A good feature could be to pass the timezone as an environmental variable in `docker run` such as:

```bash
docker run -e TZ="Europe/Athens" manios/nagios:latest
```

and configure it in both the container and Nagios.

**Comment by esticle** [comment]
+1 My hack atm:
```

# sed -i s/^'#  SSLRequireSSL'/'#  SSLRequireSSL\nSetEnv TZ \"Europe\/Paris\"'/g /etc/apache2/conf.d/nagios.conf
# killall -HUP httpd

```

**Comment by viperk1** [comment]
It looks like you can specify a global conf for the apache part. I just edited the apache section in my dockerfile and it fixed the timezone issues:

```
RUN export DOC_ROOT="DocumentRoot $(echo $NAGIOS_HOME/share)"                                        && \
    sed -i "s,DocumentRoot.*,$DOC_ROOT," /etc/apache2/httpd.conf                                     && \
    sed -i "s|^ *ScriptAlias.*$|ScriptAlias /cgi-bin $NAGIOS_HOME/sbin|g" /etc/apache2/httpd.conf    && \
    sed -i 's/^\(.*\)#\(LoadModule cgi_module\)\(.*\)/\1\2\3/' /etc/apache2/httpd.conf               && \
    echo "ServerName ${NAGIOS_FQDN}" >> /etc/apache2/httpd.conf                                      && \
    echo "SetEnv TZ ${NAGIOS_TIMEZONE}" >> /etc/apache2/conf.d/timezone.conf
```

**Comment by tr1plus** [comment]
Any update on this? I see you made some changes start of March. Checking the code either the TZ variable or setting the timezone via the nagios.cfg should work. For me I tried setting both the "Europe/Brussels", but my time remains in UTC.

Thanks!

**Comment by manios** [comment]
Hi @tr1plus ! 

Sorry for the delay. I am trying to fix the CI/CD stuff (DockerHub, Travis, Github Actions) and that's why I have postponed the release of this feature.

If you are on a hurry you can use temporarily:

```bash
docker run -d -p 8080:80 \
 -e "TZ=Europe/Brussels" \
 --name nagios \
 manios/nagios:4.4.5-tz
```

Hopefully in the following 2 weeks it will be merge to the `master` branch, with other stuff.

Please tell me if that thing works for you!
Best regards,
Christos
