### ISSUE TITLE
/bin/gosu on rancher deployment

### ISSUE THREAD

**Issue by gprakosa** [manios/docker-nagios#14]
Reference Issue: #6 

HI, @manios 

I got  some error with Rancher Deployment

```
/opt/nagios # uname -a
Linux nag4-556fdc7c5c-xgrlk 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 Linux
/opt/nagios # gosu nagios sh -c 'gosu root ping 127.0.0.1 -c 5'
error: failed switching to "root": operation not permitted
/opt/nagios # 
```
but, strange **NOT** with single docker instance run on RancherOS itself . . .

**Comment by gprakosa** [comment]
Hi, @manios 

I think I found the culprit by manage `allowPrivilegeEscalation` from false to true, it works now.
```
...
spec:
      containers:
        ...
        securityContext:
          allowPrivilegeEscalation: true
          ...
...
```

Thanks

**Comment by manios** [comment]
Hi @gprakosa !

Thank you for using my image and for the feedback about Kubernetes and Rancher!

Best regards,
Christos
