### ISSUE TITLE
4.4.6 release

### ISSUE THREAD

**Issue by esticle** [manios/docker-nagios#16]
Hi,

I see [4.4.6](https://www.nagios.org/projects/nagios-core/history/4x/) is out - will we be seeing it by any chance?

Thanks!

**Comment by manios** [comment]
Hi @esticle ,

Thanks for noticing that! I am currently refactoring the whole building process in CI/CD. As soon as I am finished I will release `v4.4.6` and will let you know in this issue.

Best regards,
Christos

**Comment by manios** [comment]
Hi @esticle ,

We are pleased to announce the release of the image tag for Nagios version `4.4.6`. This comes with updates to plugins and NRPE. For more information please have a look at [Build 2 Section in CHANGELOG](https://github.com/manios/docker-nagios/blob/master/CHANGELOG.md#build-2-2020-12-24).

Have a nice and Merry Christmas!

/cc @Dragane,@viperk1,@tr1plus
