### ISSUE TITLE
The map icons and status images?

### ISSUE THREAD

**Issue by nexusguy59** [manios/docker-nagios#21]
Hey Guys,

I noticed that these aren't working they are located in /opt/nagios/share/images/logo However i cannot figure out how to map them can someone help me with that please.

under the config file
They go in under the host definition.

icon_image              linux.png
statusmap_image    linux.gd2

Thank you for your help

**Comment by manios** [comment]
Hi @nexusguy59 ,

The default directory for logos and images is `/opt/nagios/share/images/logos/` which is already filled with icons and images. With a quick [Google search](https://www.google.com/search?client=firefox-b-d&ei=LakbYK7TF42bjLsPqZCFkAw&q=nagios+host+icon+png&oq=nagios+host+icon+png&gs_lcp=CgZwc3ktYWIQAzoECCEQClDoKFjGLGD3LWgCcAB4AIABigKIAZcGkgEFMS40LjGYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwjuncOR4c_uAhWNDWMBHSlIAcIQ4dUDCAw&uact=5) you can find [example usages](https://srparkin.wordpress.com/2011/10/18/adding-icons-to-nagios-map/).

Running with the default configuration,

```bash
docker run -d --name nagios4 -p 0.0.0.0:8080:80 manios/nagios:latest
```

I managed to make an icon show by editting the host definition of `localhost`:

```conf
define host {                                                                  
    use         linux-server    ; Name of host template to use
                                ; This host definition will inherit all variables that are defined
                                ; in (or inherited by) the linux-server host template definition.
    host_name   localhost                                                                         
    alias       localhost                                                                        
    address     127.0.0.1                                                                         
    icon_image  win40.png                                                                    
}   
```

Can you please provide more info about the steps you perform?

Thank you,
Christos

**Comment by manios** [comment]
Hi @nexusguy59 !

I am closing this issue, since there is no response for more than a month. If you have any updates you can  provide more info with a comment here.

Thank you,
Christos
