### ISSUE TITLE
check_snmp is missing from plugins

### ISSUE THREAD

**Issue by cramm** [manios/docker-nagios#22]
Hi,

you should include check_snmp in plugins since a lot of checks uses snmp.

**Comment by manios** [comment]
Hi @cramm !

Thank you for your valuable help! I have fixed the issue and you can download the latest image which includes all plugins including those (`ldap`,`snmp`,`check_pgsql`,`dbi`,`radius`,`mysql`) whose build was failing (check also #3).

Can you please give it a try?

```bash
docker pull manios/nagios:latest
# or
docker pull manios/nagios:4.4.6
```

I am closing the issue. If you find any discrepancy please post a comment here and we will take a look.

Thanks,
Christos
