### ISSUE TITLE
Tactical Overview >> Internal Server Error 500

### ISSUE THREAD

**Issue by perote2000** [manios/docker-nagios#24]
Ive made a fresh deploymen, with no custom cfg files, just executed:

docker pull manios/nagios
docker run --name nagios -p 0.0.0.0:8080:80 manios/nagios:latest

And browse to http://xxxxx:8080/nagios and home page works fine, but when I click on every link that uses path /nagios/cgi-bin/ for instance http://xxxxx:8080/nagios/cgi-bin/tac.cgi 
shows me :

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at you@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Error log File shows:
[root@xxxxx ~]# podman exec -it nagios cat /var/log/apache2/error.log
[Thu Apr 15 18:44:22.220000 2021] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.46 (Unix) PHP/7.4.15 configured -- resuming normal operations
[Thu Apr 15 18:44:22.220026 2021] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/httpd -D NO_DETACH'
[Thu Apr 15 18:44:29.194909 2021] [cgi:error] [pid 30] [client 10.3.5.101:50166] End of script output before headers: tac.cgi, referer: http://xxxxx:8080/side.php

I think there is a misscoonfigurarion in image... Ive tried docker.io/jasonrivers/nagios image and it work fine... no problem at all....

**Comment by manios** [comment]
Hi @perote2000 !

Thanks for the information! I confirm that there is a problem whith the cgi scripts. It seems the [musl libc](https://musl.libc.org/) version used in our `latest` image tag causes the issue. 

```shell
/opt/nagios# apk info musl
musl-1.2.2-r0 description:
the musl c library (libc) implementation
```

There is an ongoing discussion in #3 . Check my latest response [here](https://github.com/manios/docker-nagios/issues/3#issuecomment-822051288). I will let you know once we have a solution.

Best regards,
Christos

**Comment by manios** [comment]
Hi @perote2000  !

I have just released a new `latest` tag based on `alpine:3.11` and it throws no errors. Can you please give it a try

```shell
docker pull manios/nagios:latest
# or
docker pull manios/nagios:4.4.6
```

and provide me with feedback so we can close the issue?

Thanks,
Christos

**Comment by manios** [comment]
Ηι @perote2000 !

I am closing the issue. If you find any discrepancy please post a comment here and we will take a look.

Thanks,
Christos

**Comment by bobbintb** [comment]
I hope it isn't a problem commenting on a closed issue but I am having the same problem using the latest build. I checked and my musl version is musl-1.2.2-r3. I get the issue on these pages:

Tactical Overview
Network Outages
Availability
Alerts - Summary
Event Log
Configuration

**Comment by manios** [comment]
Hi @bobbintb !

I have created #34 to tackle the issue properly.

Thanks!
Christos
