### ISSUE TITLE
arm64?  

### ISSUE THREAD

**Issue by cranky-coder** [manios/docker-nagios#25]
any chance of being able to add arm64 arch to the image build?   This is exactly what I was looking for and then realized I am running Ubuntu 64 on my pi4s  and it's not looking for the armv7 arch but arm64.  

Thanks!

**Comment by cranky-coder** [comment]
Gentleman and a scholar!!! I woke up this morning and my k8s cluster had already pulled the image and was trying to run it!!  Much appreciated!!!

**Comment by manios** [comment]
Hi @cranky-coder !

As you have already seen, there is an `arm64` build flavour available now.

Cheers!
Christos
