### ISSUE TITLE
Error unreachable item when image build with the Dockerfile

### ISSUE THREAD

**Issue by SirTerrific** [manios/docker-nagios#29]
Hi,

I tried to build the image with the Dockerfile provide in the git but nagios didn't work correctly. All of the monitored items (ping for example) are flagged as unreachable...

Thanks.

**Comment by manios** [comment]
Hi @SirTerrific !

Can you please provide the exact `docker  build` command you are using and the error returned?

Thanks,
Christos

**Comment by manios** [comment]
Hi @SirTerrific 

I am closing this issue, since there is no response for more than a month. If you have any updates you can provide more info with a comment here.

Thank you,
Christos
