### ISSUE TITLE
build5: with update to alpine 3.14 issue 3 is back

### ISSUE THREAD

**Issue by qeepcologne** [manios/docker-nagios#33]
check_mysql_query is broken again (@see #3) i had to rollback to build4, i think it is caused by alpine update (again).

**Comment by manios** [comment]
Hi @qeepcologne !

I think that I have finally fixed it using the resolution from [alpine/aports #12601](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12601). I have tested with:

```shell
./libexec/check_mysql_query -P 3306 -H 193.62.192.245 -u anonymous  -q 'select 1'
```

and it works without any segmentation fault. Can you please give it a try

```bash
docker pull manios/nagios:latest
# or
docker pull manios/nagios:4.4.6
```

and provide me with feedback so we can close the issue?

Thanks,
Christos

**Comment by qeepcologne** [comment]
build-6 is fine, problem is gone.
