### ISSUE TITLE
Legacy Map missing

### ISSUE THREAD

**Issue by predecker** [manios/docker-nagios#36]
Hi,

I'm new to github, so maybe this is not the best place to put my correction ...
I was missing the legacy map and found out that statusmap.cgi was missing. I appreciate your lightweight approach, but two packages more to the alpine installation help a lot. I inserted

gd gd-dev \

in line 37 of the Dockerfile (just before the net-snmp-tools) and that made statusmap.cgi compile and work (at least for me). I found the solution in https://support.nagios.com/forum/viewtopic.php?f=7&t=29361

Thanks for your work,
Peter

**Comment by manios** [comment]
Hi @predecker!

Thanks for your help! I have added the dependency in `build-9` which is released today `2022-05-08`.

Please use :

```shell
docker pull manios/nagios:latest
# OR
docker pull manios/nagios:build-9
# OR
docker pull manios/nagios:4.4.7
```
to test. Also please read [docker-nagios/issues/42#issuecomment-1120467955](https://github.com/manios/docker-nagios/issues/42#issuecomment-1120467955)

Best regards ,
Chris
