### ISSUE TITLE
Mail sending fail - AARCH64

### ISSUE THREAD

**Issue by bkiss** [manios/docker-nagios#39]
### What happened?

Hi there, 

I want to move my existing nagios setup to cloud instance, Ampere ARM, my new arhitecture is:
 
docker exec -it nagios /bin/sh -c 'apk --print-arch'
aarch64

**My logs :**
wproc:   stderr line 01: /bin/sh: /bin/mail: not found

**In the console of the container:**

bash-5.0# which mail
bash-5.0# /usr/bin/mail
bash: /usr/bin/mail: No such file or directory
bash-5.0# /bin/mail
bash: /bin/mail: No such file or directory
bash-5.0# 

So it looks like there is no mail :(

Thank you in advance!

### Image information

* build: 8
* gitCommit: 69c1a3a190b865ecaf765c50c5b2dcb1042bb9e8
* homepage: https://www.nagios.com/
* maintainer: Christos Manios <maniopaido@gmail.com>
* nagiosPluginsVersion: 2.3.3
* nagiosVersion: 4.4.6
* name: Nagios
* nrpeVersion: 4.0.3

### Image architecture

arm64

### Relevant log output

```shell
wproc: NOTIFY job 115 from worker Core Worker 23 is a non-check helper but exited with return code 1272022-01-07T12:56:18.148470+00:00 c009e4ec9d5b : wproc: NOTIFY job 115 from worker Core Worker 23 is a non-check helper but exited with return code 127


wproc:   host=xxxxxx; service=SMTP; contact=xxxxx

wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;

wproc:   stderr line 01: /bin/sh: /bin/mail: not found

2022-01-07T12:56:18.148562+00:00 c009e4ec9d5b : wproc:   host=XXXXXXX; service=SMTP; contact=xxxxx

2022-01-07T12:56:18.148585+00:00 c009e4ec9d5b : wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;

2022-01-07T12:56:18.148598+00:00 c009e4ec9d5b : wproc:   stderr line 01: /bin/sh: /bin/mail: not found

2022-01-07T13:09:37.011693+00:00 c009e4ec9d5b : Auto-save of retention data completed successfully.
```

**Comment by manios** [comment]
Hi @bkiss !

Thank you for your comment. As described in the README file, this image uses [sSMTP](https://wiki.debian.org/sSMTP) as mail agent for email notifications. To help you, I added a symbolic link to `ssmtp` as you can see here:

```shell
/ $ which mail
/usr/sbin/mail
/ $ ls -l /usr/sbin/mail
lrwxrwxrwx    1 root     root            15 May  7 16:47 /usr/sbin/mail -> /usr/sbin/ssmtp
```

Best regards ,
Chris
