### ISSUE TITLE
[Bug]: logrotate not working

### ISSUE THREAD

**Issue by qeepcologne** [manios/docker-nagios#41]
### What happened?

```
1644534000] Error: Unable to rename file '/var/log/nagios/nagios.log' to '/var/log/nagios/archive/nagios-02-11-2022-00.log': Permission denied
```

### Image information

* build: 9
* gitCommit: 828015538f64cbb6a3ea961c06b37115fd3609f3
* homepage: https://www.nagios.com/
* maintainer: Christos Manios <maniopaido@gmail.com>
* nagiosPluginsVersion: 2.3.3
* nagiosVersion: 4.4.6
* name: Nagios
* nrpeVersion: 4.0.3

### Image architecture

amd64

**Comment by manios** [comment]
Hi @qeepcologne !

I am closing this issue since the image does not contain `logrotate` as far as I am concerned. Maybe this is something in your custom image?

Thanks,
Christos

**Comment by qeepcologne** [comment]
ok
