### ISSUE TITLE
feature request: nagios 4.4.7

### ISSUE THREAD

**Issue by qeepcologne** [manios/docker-nagios#42]
### What happened?

new version released some days ago, is it possible to provide update

### Image information

-

### Image architecture

amd64

**Comment by manios** [comment]
Hi @qeepcologne !

Thanks for the info! I am working on it. At the moment it is not working and Nagios 4.4.7 keeps restarting. You can see the attempts in branch [build9](https://github.com/manios/docker-nagios/tree/build9).

Any ideas on how to resolve this are welcome.

Best regards,
Christos

**Comment by qeepcologne** [comment]
did you try to disable check_for_updates ?
https://github.com/NagiosEnterprises/nagioscore/issues/861

**Comment by manios** [comment]
Hi @qeepcologne!

Indeed, by setting `check_for_updates=0` in `"${NAGIOS_HOME}/etc/nagios.cfg` it works. I have added that to be done automatically on every start. The user will see this in Nagios homeoage until the issue [nagioscore/#861](https://github.com/NagiosEnterprises/nagioscore/issues/861) is resolved.

![image](https://user-images.githubusercontent.com/1715714/167310784-bee0f91c-a538-4a83-8958-e4e362529399.png)

Please use :

```shell
docker pull manios/nagios:latest
# OR
docker pull manios/nagios:build-9
# OR
docker pull manios/nagios:4.4.7
```
to test.

Thanks,
Chris
