### ISSUE TITLE
Update to NAGIOS_VERSION=4.4.8

### ISSUE THREAD

**Issue by alfonx** [manios/docker-nagios#49]
Please update to latest  NAGIOS_VERSION=4.4.8

https://www.nagios.org/projects/nagios-core/history/4x/

**Comment by manios** [comment]
Hi @alfonx !

Thanks for your help! I have upgraded Nagios to v4.4.8 in build-10 which is released today 2022-11-17.

Please use :

```bash
docker pull manios/nagios:latest
# OR
docker pull manios/nagios:build-10
# OR
docker pull manios/nagios:4.4.8
```

to test.

Best regards ,
Chris
