### ISSUE TITLE
update to version 4.4.11

### ISSUE THREAD

**Issue by qeepcologne** [manios/docker-nagios#58]
### What happened?

please update to the latest version:
https://www.nagios.org/projects/nagios-core/history/4x/

### Image information

-

### Image architecture

amd64

**Comment by Schmoho** [comment]
potentially relevant PR https://github.com/manios/docker-nagios/pull/57

**Comment by manios** [comment]
Hi @qeepcologne , @Schmoho !

We have a new release build with Nagios `v4.4.11` and plugins `v2.4.4`. Please pull the latest images.

Thanks,
Christos
