### ISSUE TITLE
/bin/gosu x86-64 only

### ISSUE THREAD

**Issue by esticle** [manios/docker-nagios#6]
Hi,

Another quick one that is ARM specific - I noticed my localhost ping fails:

`Status Information: /bin/gosu root /bin/ping -n -W 10 -c 5 127.0.0.1 CRITICAL - Could not interpret output from ping command`

Turns out /bin/gosu is x86-64 only:

```
/opt/nagios # /bin/gosu
/bin/gosu: line 3: syntax error: unexpected end of file (expecting ")")
/opt/nagios # file /bin/gosu
/bin/gosu: setuid, setgid ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=XOzwEH6V6iJDf36Y0aCb/KPezFZThkGBKlprEwfIr/eA9pM6F66-eLmHeF5tEI/E7RX6OhdNfEiOxNqCLlW, stripped
/opt/nagios # uname -a
Linux 5ef9ed4a4110 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l Linux
/opt/nagios #
```
If I replace it with the gosu 1.11 armhf release binary (for a RPI3, and 'chmod +s' of course) we get going OK:

```
/etc # /bin/gosu nagios sh
/etc $ /bin/gosu root /bin/ping -n -W 10 -c 5 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.335 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.294 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.282 ms
^C
--- 127.0.0.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.282/0.303/0.335 ms
```

**Comment by manios** [comment]
Hi @esticle !

Thanks for finding that! I had encountered that too in my Raspberry 3 (RPI3) but I forgot to commit the fix :blush: 

I have fixed it by modifiyng the [Custom build phase hooks](https://docs.docker.com/docker-hub/builds/advanced#custom-build-phase-hooks). 

When the build is done for `latest-armv7` (it can take more than 2 hours) can you confirm if it works for you too?

Thanks,
Christos

**Comment by gprakosa** [comment]
HI, @manios 

I got  some error with Rancher Deployment

```
/opt/nagios # uname -a
Linux nag4-556fdc7c5c-xgrlk 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 Linux
/opt/nagios # gosu nagios sh -c 'gosu root ping 127.0.0.1 -c 5'
error: failed switching to "root": operation not permitted
/opt/nagios # 
```
but, strange **NOT** with single docker instance run on RancherOS itself . . .
