### ISSUE TITLE
External Command File not writable

### ISSUE THREAD

**Issue by esticle** [manios/docker-nagios#7]
Hi,

On a default install, any external command file operations (reschedule a check time for a service as an example) fails with something like:

```
Error: Could not open command file '/opt/nagios/var/rw/nagios.cmd' for update!
The permissions on the external command file and/or directory may be incorrect. Read the FAQs on how to setup proper permissions.
An error occurred while attempting to commit your command for processing.
```
I noticed that Nagios is ./configure'd with a nagcmd groupid already, so I fixed it with:

```
# chown nagios:nagcmd /opt/nagios/var/rw
# chown nagios:nagcmd /opt/nagios/var/rw/nagios.cmd
# addgroup apache nagcmd
# addgroup apache nagios
```

Arguably only nagios or nagcmd is necessary (not both) but the general advice on some searches tend to include both, YMMV.

**Comment by manios** [comment]
Hi @esticle !

Thanks for finding that! I managed to reproduce it in my my Raspberry Pi 3 (RPI3) ! :blush: 

I made a quick fix. I use the same group name, `nagios` for both `NAGIOS_CMDGROUP` and `NAGIOS_GROUP` now.Thanks!

When the build is done for `latest-armv7` can you confirm if it works for you too?

Thanks,
Christos

**Comment by esticle** [comment]
Just tried with the latest build and agree.

The issue is more that these execution events is created by Apache, therefore this has fixed it for me in the last build:

```
# addgroup apache nagios # so 'apache' is in the 'nagios' group
# killall apache # in my absence in knowing how to restart it  - this will pickup the above group change 
# sleep 10 # so presumably runsv kicks in and starts apache before you retry
```

**Comment by manios** [comment]
Hi @esticle !

Thanks for your findings and your help! I think I have fixed the issue. Can you try the new image when it is built (DockerHub is very slow with Qemu in order to build ARM container) and tell me if it works for you as well?

Thanks,
Christos

**Comment by esticle** [comment]
Thanks @manios ! Can confirm that this is correct with the latest build
