### ISSUE TITLE
Trends and histogram do not work in Nagios 4.5.3

### ISSUE THREAD

**Issue by martijnv** [manios/docker-nagios#74]
### What happened?

For anyone updating to Nagios 4.5.3: there is an issue with the trends and histogram. I thought it might be useful to share/reference that in this project. It is not an issue for this project itself:

https://github.com/NagiosEnterprises/nagioscore/issues/975

### Image information

4.5.3

### Image architecture

x86

### Relevant log output

```shell
None
```

**Comment by martijnv** [comment]
Apparantly it is fixed in 4.5.4 (from the ChangeLog of Nagios):

4.5.4 - 2024-XX-XX
------------------
* Fix inconsistent links for 'View {Trends,Alert Histogram} For This {Host,Service}' (Mauricio Faria de Oliveira)
* Fix broken links from removing AngularJS pages in 4.5.3 (Dylan Anderson)

**Comment by owendswang** [comment]
OMG. Where is 4.5.4? It's not release yet... >_<

**Comment by owendswang** [comment]
Well... It's out now. So quickly. https://github.com/NagiosEnterprises/nagioscore/releases/tag/nagios-4.5.4

**Comment by manios** [comment]
Hi @martijnv , @owendswang ! I have released a new build `build-21` with Nagios 4.5.4. Thanks for the quick info!
