### ISSUE TITLE
[Bug]: NAGIOSADMIN_USER env variable not set in cgi.cfg as authorized username

### ISSUE THREAD

**Issue by pathia** [manios/docker-nagios#78]
### What happened?

I got "It appears as though you do not have permission to view information for any of the services you requested..." whenever accessing the webpages of Nagios.

### Image information

* build: 21
* gitCommit: 786a3d6aa4e30336974c17be5c3018a538752e04
* homepage: https://www.nagios.com/
* maintainer: Christos Manios <maniopaido@gmail.com>
* nagiosPluginsVersion: 2.4.11
* nagiosVersion: 4.5.4
* name: Nagios
* nrpeVersion: 4.1.1
* org.opencontainers.image.authors: Christos Manios <maniopaido@gmail.com>
* org.opencontainers.image.description: Nagios, the Industry Standard In IT Infrastructure Monitoring
* org.opencontainers.image.documentation: https://github.com/manios/docker-nagios/blob/master/README.md
* org.opencontainers.image.licenses: MIT
* org.opencontainers.image.revision: 786a3d6aa4e30336974c17be5c3018a538752e04
* org.opencontainers.image.source: https://github.com/manios/docker-nagios
* org.opencontainers.image.title: Nagios
* org.opencontainers.image.url: https://hub.docker.com/r/manios/nagios
* org.opencontainers.image.vendor: Nagios
* org.opencontainers.image.version: 20

### Image architecture

x86

### Relevant log output

```shell
not needed.
This can be fixed by doing something like this in start_nagios.sh
sed -i "s|nagiosadmin|${NAGIOSADMIN_USER}|g" /opt/nagios/etc/cgi.cfg
```

**Comment by manios** [comment]
Hi @pathia !

To be honest at the first look I could not understand what is the problem that you describe. I managed to reproduce the issue by executing:

```bash
docker run -d --name nagios  \
  -e NAGIOSADMIN_USER="godmode" \
  -e NAGIOSADMIN_PASS="godmode"  \
  -p 0.0.0.0:8080:80  \
   manios/nagios:latest
```

Then after trying to see the Hosts and Services through the web interface I got the error shown:

```
It appears as though you do not have permission to view information for any of the hosts you requested...

If you believe this is an error, check the HTTP server authentication requirements for accessing this CGI
and check the authorization options in your CGI configuration file.
```

Thanks for your suggestion! A fix will come soon.

Best regards,
Chris

**Comment by pathia** [comment]
Thanks!

**Comment by manios** [comment]
Good morning @pathia !

A new release `build-22` is out with the fix. You can download it and test it with `docker pull manios/nagios:latest` or `docker pull manios/nagios:build-22` or `docker pull manios/nagios:4.5.4`. Please let me know if the problem has been fixed.

Thanks,
Chris

**Comment by pathia** [comment]
Good morning! 
Watchtower already downloaded it while I was asleep.
Even though I already fixed it in my setup here I'll start over tonight and see how it goes. I looked at the code changes you did and it looked promising.

**Comment by pathia** [comment]
Hi Chris, I tested with a default cgi.cfg and it nicely replaced all the authorized_for entries with my configured username.
Thanks for your quick response and action!
