### ISSUE TITLE
[Bug]: Unable to pull version 4.5.6

### ISSUE THREAD

**Issue by martijnv** [manios/docker-nagios#85]
### What happened?

Using docker pull I am unable to pull version 4.5.6

### Image information

docker pull output:

❯ docker pull manios/nagios:4.5.6

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview manios/nagios:4.5.6
Error response from daemon: manifest for manios/nagios:4.5.6 not found: manifest unknown: manifest unknow

### Image architecture

x86, amd64, arm/v6, arm/v7, arm64

### Relevant log output

```shell
None
```

**Comment by manios** [comment]
Hi @martijnv !

Thanks for pointing that ! I had forgotten to push the image tag `4.5.6`. I have done it and you can now use normally:

```bash
docker pull manios/nagios:4.5.6
```

Have a nice night!
Chris

**Comment by martijnv** [comment]
Thanks for the reply and your effort!
